### ISSUE TITLE
PG&E reading

### ISSUE THREAD

**Issue by Roguish000** [mcolyer/smartermeter#38]
hello.
I'm trying to find some simple code to read the zigbee data from my PG&E smart electric meter over here in Walnut Creek.
any suggestions?
thanks.

**Comment by mcolyer** [comment]
Sorry, unfortunately I don't have any suggestions for that as this project uses the web API exclusively.

**Comment by Roguish000** [comment]
well, thanks for the reply.
good luck with your project.
